name: Update repo on new ipfs-tag release
on:
  push:
  # workflow_dispatch:
  # schedule:
  #   - cron: '30 5,17 * * *' # run every day at 5:30am and 5:30pm UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout http-api-docs
        uses: actions/checkout@v2
      - name: Find latest go-ipfs tag
        uses: ./http-api-docs/.github/actions/latest-ipfs-tag
